#!/usr/bin/env python3
"""
Guide to reproduce original VAM model with ELBO
This script helps you understand how the original VAM model works
"""

print("="*80)
print("Original VAM Model Reproduction Guide")
print("="*80)
print()

print("【Overview】")
print("-"*80)
print("The original VAM model uses:")
print("  - Framework: JAX/Flax (not PyTorch)")
print("  - Loss Function: ELBO (Evidence Lower Bound)")
print("  - Training: Variational Inference")
print()

print("【Key Differences from Simplified Version】")
print("-"*80)
print()
print("1. Framework:")
print("   Simplified: PyTorch")
print("   Original:   JAX/Flax")
print()
print("2. Loss Function:")
print("   Simplified: Custom drift_rate_loss (supervised)")
print("   Original:   ELBO (variational inference)")
print()
print("3. Optimization:")
print("   Simplified: Direct drift rate optimization")
print("   Original:   Joint optimization of CNN + LBA parameters")
print()

print("【How to Run Original VAM】")
print("-"*80)
print()
print("Step 1: Navigate to vam directory")
print("  cd /Users/siyu/Documents/GitHub/VAM-studying/vam")
print()
print("Step 2: Install dependencies")
print("  pip install -r training_requirements.txt")
print()
print("Step 3: Train VAM model")
print("  python -m vam.training --project test --expt_name exp001")
print()
print("Step 4: Train task-optimized model")
print("  python -m vam.training --model_type task_opt --n_epochs 30")
print()
print("Step 5: Train binned RT model")
print("  python -m vam.training --model_type binned_rt --n_rt_bins 5 --rt_bin 3")
print()

print("【Understanding ELBO】")
print("-"*80)
print()
print("ELBO = Evidence Lower Bound")
print()
print("Formula:")
print("  ELBO = E_q[log p(x|z)] + E_q[log p(z)] - E_q[log q(z)] + Jacobian")
print()
print("Components:")
print("  1. log p(x|z): LBA log-likelihood (reconstruction)")
print("     - Measures how well drift rates predict RT and choices")
print("     - Uses LBA model to compute probability")
print()
print("  2. log p(z): Prior term")
print("     - Regularizes LBA parameters (a, c, t0)")
print("     - Assumes log-normal distribution")
print()
print("  3. log q(z): Entropy term")
print("     - Measures uncertainty in variational posterior")
print("     - Encourages exploration")
print()
print("  4. Jacobian: Density adjustment")
print("     - Handles variable transformation")
print("     - Ensures probability conservation")
print()

print("【Key Files to Study】")
print("-"*80)
print()
print("1. vam/vam/models.py")
print("   - VAM class: Combines CNN + LBAVI")
print("   - CNN class: Generates drift rates")
print("   - LBAVI class: Variational inference for LBA")
print()
print("2. vam/vam/lba.py")
print("   - LBA model implementation")
print("   - lba_logp: Computes log-likelihood")
print("   - generate_vam_rts: Simulates RT and choices")
print()
print("3. vam/vam/training.py")
print("   - Trainer class: Main training loop")
print("   - vam_train_step: Training with ELBO")
print("   - vam_eval_step: Evaluation")
print()
print("4. vam/vam/config.py")
print("   - ConfigDict pattern for configuration")
print("   - Model hyperparameters")
print()

print("【Next Steps】")
print("-"*80)
print()
print("1. Read the paper:")
print("   vam/Jaffe et al. - 2025 - An image-computable model of speeded decision-making.pdf")
print()
print("2. Study the code:")
print("   - Start with models.py to understand architecture")
print("   - Then read lba.py to understand LBA model")
print("   - Finally study training.py to understand ELBO optimization")
print()
print("3. Run experiments:")
print("   - Train VAM on Flanker task")
print("   - Analyze drift rates and model behavior")
print("   - Compare with simplified PyTorch version")
print()

print("【Comparison Table】")
print("-"*80)
print()
print("| Aspect           | Simplified (PyTorch) | Original (JAX/Flax) |")
print("|------------------|----------------------|---------------------|")
print("| Framework        | PyTorch              | JAX/Flax            |")
print("| Loss Function    | Custom loss          | ELBO                |")
print("| Training Method  | Supervised learning  | Variational inference|")
print("| Optimization     | Drift rates only     | CNN + LBA jointly   |")
print("| Cognitive Model  | None                 | Full LBA model      |")
print("| RT Prediction    | Simplified           | Full LBA simulation |")
print("| Interpretability | Low                  | High                |")
print()

print("【Recommendation】")
print("-"*80)
print()
print("To better understand the model:")
print("  1. Start with the simplified PyTorch version")
print("     - Easier to understand basic concepts")
print("     - Quick to experiment")
print()
print("  2. Then study the original JAX/Flax version")
print("     - Complete cognitive modeling")
print("     - Full ELBO optimization")
print("     - Better understanding of VAM")
print()
print("  3. Compare results from both versions")
print("     - Understand why ELBO is necessary")
print("     - Appreciate the cognitive modeling approach")
print()
